### ISSUE TITLE
Create a cicd pipeline 

### ISSUE THREAD

**Issue by syedsfayaz** [HewlettPackard/Jenkins-stats#1]
Is it possible to create a cicd pipeline using build results from dependent jobs.

Ex.     A --> B --> C --> D

    A = step 1 -> step 2 -> step  3

**Comment by mulcahys** [comment]
Yes, you can build pipelines in Jenkins now - see https://jenkins.io/doc/book/pipeline/jenkinsfile/

**Comment by syedsfayaz** [comment]
Sorry, What I mean is show the pipeline on Dashboard.  For example I have multiple application I want to track their process at one place. Since we are pulling all results here We can show it on one dashboard. (We have a requirement to pull data from different jenkins servers and show status on one page. The jobs are interlinked with each other)

This just my Idea and can be altered based on limitations we have in this tool.

This will be the top page for all applications. 
![image](https://user-images.githubusercontent.com/26099918/62217012-b5ce3a80-b35e-11e9-95b2-9d5bdc0c498b.png)

This will be the details of individual application.
![image](https://user-images.githubusercontent.com/26099918/62217033-c41c5680-b35e-11e9-96e6-f1d6f0f1f377.png)
