### ISSUE TITLE
Skipping simple test builds

### ISSUE THREAD

**Issue by forgondolin** [HewlettPackard/Jenkins-stats#5]
Hello, 
I made some test jobs for testing this script, simple jobs with 2 steps, and when I run this, it returns a error.
What can I do to bypass this?
![image](https://user-images.githubusercontent.com/43958948/83048221-9efc8100-a01f-11ea-9904-d8510a9ced9e.png)

**Comment by mulcahys** [comment]
Hi @forgondolin - this was used primarily for Jenkins jobs triggered by OpenStack Zuul (https://docs.openstack.org/infra/zuul/) and relies on some additional metadata provided by Zuul on the jobs (see https://github.com/HewlettPackard/Jenkins-stats/blob/eeecf45a1e073f0ff94740228c59dcfcdd1a5b0e/get_jenkins_stats.py#L386 for the parsing of those fields and https://github.com/HewlettPackard/Jenkins-stats/blob/eeecf45a1e073f0ff94740228c59dcfcdd1a5b0e/get_jenkins_stats.py#L397 for the TODO to make this more generic). You'll either need to add similar metadata to your jenkins jobs or patch the tool to implement alternate logic around these fields (although note that the subsequent plotting relies on those parsed fields to generate some of the graphs).

Thanks
